BioImage-Archive/bia-integrator

- static-sitegen/scripts/generate_image_page.py
- static-sitegen/templates/image-landing.html.j2
- tools/scripts/assign_images_from_yaml.py
- tools/scripts/convert_from_structured_fileset.py
Currently we read the license from the original BioStudies entry on ingest, which is part of our data model. However, when we render the license on generated image pages, we always show CC0, which is incorrect. This PR fixes this for the two licenses we allow for web submission.
> Display the correct license on generated image pages

- tools/scripts/generate_representative_image_and_set_to_default.py
- tools/scripts/generate_thumbnail.py
On deletion of preview.py there was a stray import in scripts/generate_thumbnail.py and scripts/generate_representative_image_and_set_to_default.py was broken. This PR is an attempt to fix the issues. However, it is best @matthewh-ebi reviews to ensure changes fit in with intended use of new rendering scheme.
> Fix issues due to deletion of preview.py

- tools/snakemake/Snakefile
Make the selection of the representative image robust to failures during conversion to zarr stage (rule generate_representative_image) of Snakemake pipeline. We now loop through candidates and select the first one that was successfully converted. Closes #34
> Select a successfully converted image for representative image rule

- tools/scripts/assign_zipped_zarr_from_filerefs.py
- tools/scripts/generate_image_download_size_annotations.py
- tools/scripts/summarise_study_filetypes.py
- tools/snakemake/Snakefile
This branch allows the current snakemake workflow to handle zarr files using the existing remote_zipped_zarr_to_s3.py script. It currently does not distinguish between OME and non-ome zarrs. It simply downloads zarrs unzips if necessary and uploads to S3.
Fixes issues #37 and #38 and allows #27 to be closed.
> Handle zarrs in snakemake workflow

- static-sitegen/scripts/generate_dataset_page.py
- static-sitegen/scripts/generate_image_page.py
- static-sitegen/scripts/utils.py
The addition of the zipped zarrs to the snakemake workflow introduced a bug where the download urls for the zipped zarr files were not being added to the dataset and image pages during static_site page generation. This PR fixes it.
> Fix Download URL for zipped_zarrs in dataset and image pages

- tools/snakemake/Snakefile
This PR is a small change to fix a bug that was causing some images to be missed during the conversion stage. 
The only file affected was tools/snakemake/Snakefile.
The regex used to select filenames in the 'aggregate_converted_im_reps' function was substituted by a python lambda expression.
> Fix bug causing some images to be missed when converting to zarr

- static-sitegen/README.rst
- static-sitegen/deploy-pages-staging.sh
- static-sitegen/scripts/generate_image_page.py
- static-sitegen/templates/collection-vem-landing.html.j2
- static-sitegen/templates/image-landing.html.j2
This PR:
a) Updates the VEM collection to use the AI datasets collection landing style.
b) Changes neuroglancer link handling (only display if the link exists as an attribute, since it doesn't work well for many images).
c) Adds a deploy script to push to the newly provisioned staging bucket for pages (so we can test without breaking the existing pages).
New VEM pages visible here:
https://uk1s3.embassy.ebi.ac.uk/bia-pages-staging/pages/vem.html
> Update VEM collection

- static-sitegen/scripts/build_collection_site.py
- static-sitegen/scripts/generate_collection_page.py
- static-sitegen/scripts/generate_dataset_page.py
- static-sitegen/scripts/generate_image_page.py
- static-sitegen/scripts/utils.py
- static-sitegen/templates/dataset-landing.html.j2
- tools/scripts/extract_ome_metadata.py
- tools/scripts/list_ngff_uri_mappings.py
This is a rehash of #73 with cleaner commits. It allows generation of static pages using the API. However, it does not address the recent issue on the use of load_and_annotate_study (except in the static-sitegen/generate_image_page.py script).
> Generate static page artefacts via api

- tools/bia_integrator_tools/io.py
- tools/scripts/remote_zipped_zarr_to_s3.py
Check download file size and allow retries if size is not the expected filesize.
Also included a modification to allow for zipped zarrs not containing a single top level directory i.e. not structured as 'x.zarr/0'
Now allows e.g.
x.zarr
- .zattrs
- .zgroup
- OME
- 0
> Make copying from remote to local more robust by checking file sizes and give more flexiblity to zarr structure

- tools/snakemake/Snakefile
I've specifically not added so env vars to this patch because they have sane defaults
> This makes snakemake check for env variables and warn you if they're not set

- tools/bia_integrator_tools/biostudies.py
Added a custom header to lines using requests.get to pull data from biostudies as they reject the standard python header due to a DOS attack in December 2023.
> Use custom header with requests library as biostudies rejects standard python header (due to DOS attack)

- tools/bia_integrator_tools/cli.py
- tools/bia_integrator_tools/omezarrmeta.py
- tools/bia_integrator_tools/rendering.py
- tools/scripts/annotate_study_from_zarr.py
- tools/scripts/fetch_ome_metadata_for_all_images_in_study.py
- tools/scripts/get_axis_names_from_bia_zarr.py
bia_integrator_tools/cli.py
Typer does not seem to allow two command line arguments with one being optional, therefore changed accession-id to be an option to allow dual use of image show. If one argument -> image UUID,
or one argument-> image alias and --accession-id option
bia_integrator_tools/omezarrmeta.py
Make 'metadata' field in MultiScaleImage optional as .zattrs from S-BIAD852 did not have this
bia_integrator_tools/rendering.py
Modify assignment of dimension sizes for multiscale images to use info from 'axes' attr as opposed to assuming tczxy order especially when one dimension is missing. Missing dimensions are implicitly assumed to have size=1
scripts/fetch_ome_metadata_for_all_images_in_study.py Add try block to handle case where NGFF has no OME dir …
> Fix misc issues to allow snakemake pipeline to run with API

- tools/bia_integrator_tools/cli.py
* Stop 'images list' command from printing each image twice
* change variable names of collection commands to reflect that
study uuids are used, not study accession_ids
* Include study uuid in 'studies list' command
> Minor fixes to bia_integrator_tools.cli

- api/Readme.md
- api/src/tests/test_image.py
- api/src/tests/util.py
Issue: the tests were more likely to accidentally generate duplicate UUIDs on Macs that linux when batch creating images or files. This was due to the less fine-grained time resolution. Coupled with the api returning 201s when the exact same study is attempted to be created (considered okay, but the behaviour should probably have control flags for it), tests would sometimes not add the expected number of images/files to the DB and fail.
This PR changes how groups of images/files are created in order to 1. make sure they have different UUIDs (by incrementing the input to the generate UUID), and 2. also varies the contents of the metadata, so that a more obvious error will be hit if 2 UUIDs were the same.
Also updates to the readme about setting up VSCode tests, expected poetry errors when …
> updated UUID generation and bulk file and image generation in tests

- api/src/tests/test_file_reference.py
- api/src/tests/test_image.py
- api/src/tests/test_study.py
- api/src/tests/util.py
Updated tests to use uuid4 (random uuid generation) & avoid incrementing global variables as Craig suggested. 
A number of tests were relying on generated documents having incrementally increasing uuids when created. This allowed them to compare results since the api returns them sorted by UUID by default. Therefore the tests had to be updated to cope with the documents being returned in a different order to their creation.
Also, a little fix in one of the tests where i failed to save & commit a variable name change.
> made tests independent of order of results when not relevant

- clients/python/bia_integrator_api/util.py
- clients/python/example/readonly_start_here.py
Add readonly client builder, needed for nice explorer code (wip).
Some things ignored, to decide next wek
* do we keep simple_client (the private version) named as it is? get_client and simple_client in the same file might be confusing, but this means a rename everywhere we use a client
* do we add the api server as-is in the LB so we can get rid of the hardcoded ip and no host checking (get_client assumes yes, for tidyness)
> Add readonly client builder

- api/Readme.md
- api/src/app.py
- api/src/tests/util.py
- api/src/tests_load/common/util.py
- clients/openapi.json
- clients/python/bia_integrator_api/api/private_api.py
- clients/python/bia_integrator_api/api/public_api.py
- clients/python/bia_integrator_api/docs/PrivateApi.md
- clients/python/bia_integrator_api/docs/PublicApi.md
- clients/python/bia_integrator_api_README.md
Changes needed to make the api work under the TM reverse proxy
* move openapi.json, docs out of root to versioned path
* remove /api/ prefix from root. This is so clients get generated with /vN/... paths and then we can configure clients to use https://ebi.ac.uk/bioimage-archive/api as the base (instead of https://ebi.ac.uk/bioimage-archive)
These are *very* breaking changes, all fixable with a client update (once the branch is merged in)
> Remove api prefix

- api/src/api/annotator.py
- api/src/api/private.py
- api/src/api/public.py
- api/src/models/repository.py
This is deployed already, there was an issue with a 500 error when doing 5(parallel)*44 (sequential) requests getting all images of S-BIAD582. I think somewhere in there a cached db client was reused across requests (maybe for a pending request), but we explicitly close the connection before applying (or not) any annotations.
Updated from the initial PR to only close the connection if apply_annotations=True (so in that case, the 500 error would still happen, but we don't regularly use that now)
> Fix race condition when db gets reused

- bia-export/.vscode/settings.json
- bia-export/README.md
- bia-export/bia_export/cli.py
- bia-export/bia_export/website_conversion.py
- bia-export/bia_export/website_models.py
- bia-export/pyproject.toml
- bia-export/test/conftest.py
- bia-export/test/input_data/biosample/S-BIADTEST/64a67727-4e7c-469a-91c4-6219ae072e99.json
- bia-export/test/input_data/biosample/S-BIADTEST/6950718c-4917-47a1-a807-11b874e80a23.json
- bia-export/test/input_data/experimental_imaging_datasets/S-BIADTEST/47a4ab60-c76d-4424-bfaa-c2a024de720c.json
- bia-export/test/input_data/image_acquisitions/S-BIADTEST/c2e44a1b-a43c-476e-8ddf-8587f4c955b3.json
- bia-export/test/input_data/specimen_imaging_preparation_protocols/S-BIADTEST/7199d730-29f1-4ad8-b599-e9089cbb2d7b.json
- bia-export/test/input_data/studies/S-BIADTEST.json
- bia-export/test/output_data/bia_export.json
- bia-export/test/test_local_convert.py
Set up the basics of the bia-export package to create studies for website from json files
> created bia-export base package

- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
- bia-shared-datamodels/test/utils.py
These enums were created to deal with different types at the end of the submitted_in_dataset_uuid paths, but we think this could be better handled by using two subclasses (thought this might introduce the same issue with the link from derived image -source_image-> file representation). In any case, this should probably be looked into when desiging the UUID validation & have more thinking about it (perhaps a design doc). Removing for now, and cut this ticket https://app.clickup.com/t/86956e5g9 to track the follow-up work.
> removed dataset type enums for validation

- bia-export/bia_export/website_models.py
- bia-export/test/input_data/experimental_imaging_datasets/S-BIADTEST/47a4ab60-c76d-4424-bfaa-c2a024de720c.json
- bia-export/test/input_data/studies/S-BIADTEST.json
- bia-export/test/output_data/bia_export.json
- bia-ingest-shared-models/bia_ingest_sm/conversion/annotation_method.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/biosample.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/file_reference.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/image_acquisition.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_growth_protocol.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_imaging_preparation_protocol.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/study.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/utils.py
- bia-ingest-shared-models/test/utils.py
- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
See: https://app.clickup.com/t/86956q84r
Also updated website export code to use input that are at least as complex as the BIA data models (i.e. with the various api fields), since it will make using the clients easier.
> disallowed extra fields in models, and updated ingest and export code to handle these

- .github/workflows/core.yaml
- bia-shared-datamodels/test/utils.py
@sherwoodf Is this what you were thinking?
Added a matrix to the current CI so that it tests multiple folders. Negative here is that someone will need to edit the GitHub ci to add anymore subproject to testing
> CI Testing multiple projects (not clean)

- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
- bia-shared-datamodels/src/bia_shared_datamodels/exceptions.py
For https://app.clickup.com/t/86956qv26
Not tested, api still wip
> Shared models mongofy

- bia-export/test/input_data/experimental_imaging_datasets/S-BIADTEST/47a4ab60-c76d-4424-bfaa-c2a024de720c.json
- bia-export/test/output_data/bia_export.json
- bia-export/test/test_local_convert.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
- bia-ingest-shared-models/test/utils.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
- bia-shared-datamodels/test/utils.py
Created an 'associations' entry in the attributes of a dataset to store the information provided by biostudies submitters 'unchanged'.
This is generally useful if we ever need to regenerate submissions, but currently will be used to link together elements when storing in files.
See: https://app.clickup.com/t/86956n8mj
> add associations as attribute to datasets

- api/.vscode/settings.json
- api/Dockerfile
- api/api/app.py
- api/api/constants.py
- api/api/exceptions.py
- api/api/models/repository.py
- api/api/private.py
- api/api/public.py
- api/api/tests/test_dummy.py
- api/api/tests/test_minimal.py
- docker-compose.yml
To test:
* `docker compose up -d --build`
* go to http://localhost:8080/docs and create/get objects
Actual changes:
* the one test that creates/gets a study (`tests/test_minimal.py`)
* `api/private`, `api/public`
> Api shared datamodels

- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
- bia-shared-datamodels/test/test_shared_models.py
- bia-shared-datamodels/test/utils.py
Would like to get some feedback on this test / util structure before i go change all the util methods, as that will take a while.
1. Created a COMPLETE/MINIMAL enum in the utils
2. Instead of the utils methods returning a 'study' or other object, they return a dictionary. They also accept the enum value to modify the dictionary that gets returned.
3. The tests use the dictionary method to get UUIDs for linked objects (i.e. through get_study_dict()["uuid"])- this keeps the dependencies between the different objects obvious, but should reduce blanket test failing when models are changed, making debugging easier.
Also leaving a comment about minimal testing missing out some objects in the code - it's clearer to see in context.
Model changes: these are to a) to make definitions that are …
> example new test format

- .github/workflows/publish_container.yaml
- api/Dockerfile
- Old changes broke the deployment for the main api image build.
- Issue was that the CI was quite specific, modified it to be more general
- Also make the building caching faster
> Fixing more docker related stuff

- bia-ingest-shared-models/bia_ingest_sm/biostudies.py
- bia-ingest-shared-models/bia_ingest_sm/config.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/annotation_method.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/biosample.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/file_reference.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/image_acquisition.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_growth_protocol.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_imaging_preparation_protocol.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/study.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/utils.py
- bia-ingest-shared-models/test/data/file_list_study_component_2.json
- bia-ingest-shared-models/test/test_file_reference.py
- bia-ingest-shared-models/test/test_shared_models.py
- bia-ingest-shared-models/test/utils.py
Modify creation of FileReference during ingestion to align with new agreed format
FileReference now contains field pointing to its parent dataset
Write tests for ingestion of FileReference
> Update file reference

- bia-ingest-shared-models/bia_ingest_sm/biostudies.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/file_reference.py
Fix error due to formation of url from file paths on windows
during CI/CD using `as_posix` method of `Path`
> Fix windows path error

- .pre-commit-config.yaml
- README.md
- ruff.toml
- We had a go at using precommit hooks in https://github.com/BioImage-Archive/bia-agent/blob/main/.pre-commit-config.yaml and it was fine/good
- Added them here to for formatting the repo
- N.B that you can't use black and ruff-format together as they can end up disagreeing
Also note that if you make a commit that the ruff formatter doesn't like, it'll make the changes to the file then you'll have to add the file again.
If you add a file with bad linting (unused variable) the commit won't pass and you'll have to find the issue.
Currently missing: linting and formatting the webdeveloment stuff
> Precommit hooks

- api/api/app.py
- api/api/models/repository.py
- api/api/private.py
- api/api/public.py
- api/api/tests/conftest.py
- api/api/tests/test_minimal.py
- bia-export/bia_export/website_conversion.py
- bia-export/bia_export/website_models.py
- bia-export/test/output_data/bia_export.json
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_imaging_preparation_protocol.py
- bia-ingest-shared-models/test/utils.py
- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
- bia-shared-datamodels/test/test_shared_models.py
For https://app.clickup.com/t/86959dg0w , https://app.clickup.com/t/869527km2
Adding `ObjectReference` as it as (with the runtime validation hooks) just so we don't lose it when we squash, in case we ever have a usecase for it. Will make a PR deleting that part (so ObjectReference will just be a container for the link target) after that
Not fully tested, but tests should cover "one of each" for the major usecases (validating that a dependency object exists, and generating reverse links)
> Api reverse links

- bia-export/bia_export/cli.py
- bia-export/bia_export/website_conversion.py
- bia-export/test/output_data/bia_export.json
- bia-ingest-shared-models/bia_ingest_sm/biostudies.py
- bia-ingest-shared-models/bia_ingest_sm/cli.py
- bia-ingest-shared-models/bia_ingest_sm/cli_logging.py
- bia-ingest-shared-models/bia_ingest_sm/config.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/annotation_method.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/biosample.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/file_reference.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/image_acquisition.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_growth_protocol.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_imaging_preparation_protocol.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/study.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/utils.py
- bia-ingest-shared-models/test/conftest.py
- bia-ingest-shared-models/test/test_file_reference.py
- bia-ingest-shared-models/test/test_shared_models.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
This PR adds support for running ingest and export on multiple studies at once.
bia_ingest_sm
- Make ingest CLI accept a list of accession IDs and process them all
- Moved some log statements from info to debug, and added -v option to print debug logs
- Used rich to create colour code CLI output and make a summary table
Example CLI terminal output running `poetry run biaingest ingest S-BIAD978 S-BIAD999`
bia_export
- create create_studies method that creates dictionary of website study json with the accession id as they keys for use in the website
> Multi study ingest & export

- bia-ingest-shared-models/bia_ingest_sm/biostudies.py
- bia-ingest-shared-models/test/conftest.py
- bia-ingest-shared-models/test/test_bia_ingest_cli.py
- bia-ingest-shared-models/test/test_file_reference.py
- bia-ingest-shared-models/test/utils.py
- core/pyproject.toml
Add tests to ensure CLI writes out expected files
> Tests for cli

- .dockerignore
- .github/workflows/api.yaml
- .github/workflows/api_kube.yaml
- api/helm-chart/Chart.yaml
- api/helm-chart/templates/deployment.yaml
- api/helm-chart/templates/tests/api_tests.yaml
- api/helm-chart/values.yaml
- api/pyproject.toml
https://app.clickup.com/t/8695g4xcg
To remove the failing api tests that we have been ignoring since starting api v2 (should have probably been part of the first PR there)
So for the api now, we only run `test_minimal.py` (the tests for the new api)
> Remove / fix api v1 tests failing

- api/api/models/repository.py
- api/api/public.py
- api/api/tests/conftest.py
- api/api/tests/test_minimal.py
- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
For https://app.clickup.com/t/8695ft0bh
Ended up adding a `workaround_*` attribute to ObjectReference instead of adding manually (like in 1st commit) because that made referenced object validation a lot messier. It's relatively isolated / easy to change when we disambiguate the models (we can just search for the field)
Not sure if I should put the example in `test_known_bug_should_not_pass_but_does_union_reference_typed_lists_not_exclusive` down as a "known issue" or if it's worth fixing. I thing it also came up yesterday that we might have a usecase where we do actually want to mix the union types
> Manually type ambiguous links

- bia-ingest-shared-models/bia_ingest_sm/conversion/annotation_method.py
- bia-ingest-shared-models/test/utils.py
Changed the default to None for some optional fields since we should always return 'null' in json for these and never ""
> None defaults for optional annotation fields

- bia-ingest-shared-models/bia_ingest_sm/cli.py
- bia-ingest-shared-models/bia_ingest_sm/cli_logging.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/annotation_method.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/biosample.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/experimentally_captured_image.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/image_acquisition.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/image_annotation_dataset.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_growth_protocol.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_imaging_preparation_protocol.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/study.py
- bia-ingest-shared-models/bia_ingest_sm/conversion/utils.py
- bia-ingest-shared-models/test/conftest.py
We currently only tabulate errors when some object fails pydantic model validation. If we e.g. just don't create any dataset objects this counts as a success.
I thought it would be useful to track how many objects get created, and flag when unexpected values crop up.
E.g. run:
```
poetry run biaingest ingest S-BIAD534   
```
And you should get: 
```
-------- Starting ingest of S-BIAD534 --------
INFO     Fetching submission from https://www.ebi.ac.uk/biostudies/api/v1/studies/S-BIAD534                                                                            biostudies.py:140
INFO     Written /Users/fsherwood/.cache/bia-integrator-data-sm/studies/S-BIAD534.json                                                                                       study.py:81
INFO     Created …
```
> added logging of creation count

- api/api/app.py
- api/api/auth.py
- api/api/models/repository.py
- api/api/private.py
- api/api/public.py
- api/api/tests/test_minimal.py
https://app.clickup.com/t/8695mu9k9
Looks like get_db defined previously was never actually used, and fastapi was DI-ing a new instance of Repository (-> the exposed params). Changed how we request db instances in handlers + small change&comment to Repository to make this harder to misconfigure in the future
> Fix db params exposed through api

- bia-export/bia_export/website_export/datasets_for_images/models.py
- bia-export/bia_export/website_export/datasets_for_images/retrieve.py
- bia-export/bia_export/website_export/datasets_for_images/transform.py
- bia-export/bia_export/website_export/images/models.py
- bia-export/bia_export/website_export/images/retrieve.py
- bia-export/bia_export/website_export/images/transform.py
- bia-export/bia_export/website_export/studies/models.py
- bia-export/bia_export/website_export/studies/retrieve.py
- bia-export/bia_export/website_export/studies/transform.py
- bia-export/test/input_data/experimental_imaging_datasets/S-BIADTEST/47a4ab60-c76d-4424-bfaa-c2a024de720c.json
- bia-export/test/output_data/bia_image_export.json
Pydantic was compaining when trying to create objects due to a model mis-match, despite them functionally being the same e.g.
```
class Specimen (BaseModel)
sample_of: List[bia_shared_models.BioSample] = Field(
description="""The biological matter that sampled to create the specimen."""
)
```
will fail validation for a dictionary of the form:
```
{
sample_of: [
(api_client.BioSample( ...))
]
}
```
I switched to using client models as much as possible (except for a few type hits where i deal with higher level classes that aren't in the clients).
I could have instead called .model_dump() in a bunch of places, but i'm not sure that's that helpful, and i think it's better that the file version of the export code uses the same models as the api version.
Changes ended up added the default_open …
> Export to use Client Models

- api/api/public.py
- clients/openapi.json
- clients/python/Readme.md
- clients/python/bia_integrator_api/api/private_api.py
- clients/python/bia_integrator_api/api/public_api.py
- clients/python/bia_integrator_api/docs/PrivateApi.md
- clients/python/bia_integrator_api/docs/PublicApi.md
- clients/python/bia_integrator_api_README.md
Minor changes to client docs, `get_studies` was missing
Removed placeholder example custom endpoint (because we have `get_studies` now)
> Clarify docs

- bia-ingest/bia_ingest/conversion/experimentally_captured_image.py
- bia-ingest/bia_ingest/conversion/specimen.py
- bia-ingest/test/utils.py
Following discussion with ﻿@Francois we agreed to change the format of associating SpecimenImagingPreparationProtocol, SpecimenGrowthProtocol and Biosample with a BIA Specimen object. 
See [https://app.clickup.com/t/8695fqxpy](https://app.clickup.com/t/8695fqxpy)
The current method creates one Specimen object per unique association in each study component (i.e. 3 unique associations ➝. 3 Specimens)
This PR modified it to create only one Specimen per dataset (study component) irrespective of the number of unique associations in the dataset. The fields of the Specimen object will contain lists of uuids to the various sub-objects.
> Create one bia_model_data.Specimen object per dataset

- bia-ingest/bia_ingest/biostudies.py
- bia-ingest/bia_ingest/cli_logging.py
- bia-ingest/test/test_bia_ingest_cli.py
- bia-ingest/test/utils.py
Pydantic requires a default value to be set for a field in order for it to actually be optional.
When BioStudies returns file lists they can return file objects with an attribute that has a name but no value key if the column is empty.
Updated the tests to have an example of this, and updated bia_ingest_cli to use a fixture so that pydantic doesn't error when loading the tests, only a run time.
According to the results spreadsheet, this might allow us to ingest another ~40-90 studies.
> Fix ingest errors

- bia-export/test/test_local_convert.py
> tests were not failing locally, but were failing in the github actions run. Trying to change the logic to to see if the field order is different in some objects.
The issue was that i'd not run poetry update locally, and the client gets imported as an external dependency (and had been updated)
Text expectations were updated separately (oops) I still think this change will help make the tests less brittle.
> fix tests in github run

- bia-export/bia_export/website_export/studies/retrieve.py
- bia-export/test/output_data/bia_study_export.json
API logic had the image and file counts the wrong way round. Local file logic didn't have counting for images at all.
> fix image counts in local and API

- bia-ingest/bia_ingest/cli.py
- bia-ingest/bia_ingest/cli_logging.py
- bia-ingest/bia_ingest/conversion/experimentally_captured_image.py
- bia-ingest/bia_ingest/conversion/image_representation.py
This PR attempts to print a summary of models created and/or errors encountered when creating image representations. However, the output generated is not strictly correct - as only one Experimentally Captured Image (ECI) is created for all representations of the same file reference uuid(s). However, the current code logs creation of an ECI for each representation - thus overstating the number of ECIs created.
> Print summary of models created/errors when creating image representations

- bia-ingest/bia_ingest/conversion/experimental_imaging_dataset.py
- bia-ingest/bia_ingest/conversion/specimen.py
While testing ingest i noticed i was getting uncaught exceptions for specimen creation. This change adds try-except and then log. e.g. for S-BIAD1006 (not this has a lot files)
```
INFO     Created SpecimenImagingPreparationProtocol. Count: 0                                                                                                    utils.py:37
INFO     Created SpecimenGrowthProtocol. Count: 0                                                                                                                utils.py:37
ERROR    Failed to create Specimen                                                                                                                               utils.py:26
INFO     Created ExperimentalImagingDataset. Count: 1 …
```
> add try-except and log for specimen creation

- bia-ingest/bia_ingest/biostudies.py
- bia-ingest/bia_ingest/cli.py
- bia-ingest/test/conftest.py
- bia-ingest/test/data/S-BIADTEST_INFO.json
- bia-ingest/test/test_bia_ingest_cli.py
https://app.clickup.com/t/8695y91m7
Added check using the biostudies info tables before trying to process filelists
check has a y/N question for any studies with more than 200k files.
Example command to test:
poetry run biaingest ingest  S-BIAD1069 --process-filelist=skip --dryrun
> added check for count of files and dryrun mode

- bia-ingest/bia_ingest/ingest/annotation_method.py
- bia-ingest/bia_ingest/ingest/biosample.py
- bia-ingest/bia_ingest/ingest/biostudies/submission_parsing_utils.py
- bia-ingest/bia_ingest/ingest/generic_conversion_utils.py
- bia-ingest/bia_ingest/ingest/image_acquisition.py
- bia-ingest/bia_ingest/ingest/specimen_growth_protocol.py
- bia-ingest/bia_ingest/ingest/specimen_imaging_preparation_protocol.py
- bia-ingest/bia_ingest/ingest/study.py
Fix to bug arising from difference in cases of names of some sections in submission tool forms and BIA yaml template. E.g.
`Sample preparation protocol` in [S-BIAD1327](https://www.ebi.ac.uk/biostudies/bioimages/studies/S-BIAD1327) submitted using submission tool and `Sample Preparation Protocol` in [S-BIAD1117](https://www.ebi.ac.uk/biostudies/bioimages/studies/S-BIAD1117) submitted using yaml template.
This fix creates a function to access dictionaries using case insensitive keys and is applied to all instances in ingest where mapping occurs using names from biostudies sections.
> Make accessing values of dicts created from sections during ingest insensitive to case of keys

- bia-ingest/bia_ingest/biostudies/api.py
- bia-ingest/bia_ingest/biostudies/v4/study.py
- bia-ingest/bia_ingest/cli_logging.py
Also fixes failure check in logging for non-v4 studies
to test with empty link object:
poetry run biaingest ingest --process-filelist skip --dryrun S-BSST310 -v    
to test with link object without url field, only attributes:
poetry run biaingest ingest --process-filelist skip --dryrun S-BSST229 -v    
ticket: https://app.clickup.com/t/8696v7cvz
> allow empty urls or empty objects from biostudies submission

- bia-ingest/bia_ingest/bia_object_creation_utils.py
- bia-ingest/bia_ingest/biostudies/v4/bio_sample.py
- bia-ingest/bia_ingest/biostudies/v4/dataset.py
- bia-ingest/bia_ingest/biostudies/v4/growth_protocol.py
- bia-ingest/bia_ingest/biostudies/v4/image_acquisition_protocol.py
- bia-ingest/bia_ingest/biostudies/v4/study.py
- bia-ingest/bia_ingest/cli.py
- bia-ingest/bia_ingest/cli_logging.py
- bia-ingest/test/data/biad_v4/S-BIADTEST.json
Update to deal with ontology structured subsections in image acquisitions and biosamples a good study to test with is:
`poetry run biaingest ingest --process-filelist skip S-BIAD43 -v -c`
https://app.clickup.com/t/8696v7mpx
Also updated the study -> processing mode list to cover some of the bia-agent ingested studies. We could alternatively try to map on other keys in the submission.
https://app.clickup.com/t/8696v7zke
> deal with ontology values in subsections of protocols/biosample

- bia-export/README.md
- bia-export/bia_export/website_export/studies/models.py
- bia-export/bia_export/website_export/studies/retrieve.py
- bia-export/bia_export/website_export/studies/transform.py
- bia-export/test/input_data/dataset/S-BIADTEST/21999a9f-6f16-45d4-91c9-ed46cbfe015c.json
- bia-export/test/input_data/dataset/S-BIADTEST/47a4ab60-c76d-4424-bfaa-c2a024de720c.json
- bia-export/test/input_data/dataset/S-BIADTEST/850a1ca3-9681-4a8a-b625-477936fcb954.json
- bia-export/test/output_data/bia_dataset_export.json
- bia-export/test/output_data/bia_study_export.json
We now store the all the relevant uuids in the dataset in order to create images, so using that instead of trying to re-use the associations that are also stored as-is in attributes.
> updated export to use new association structure in attributes

- bia-ingest/bia_ingest/biostudies/generic_conversion_utils.py
- bia-ingest/bia_ingest/biostudies/v4/study.py
- bia-ingest/bia_ingest/cli.py
- bia-ingest/bia_ingest/cli_logging.py
The AssertionError seemed to have no message, which led to studies that did not return a 200 from the biostudies api to be labelled as successes. My change makes it less clear why it failed (could be due to validation failing or not getting a 200, but in either case we're likely to run it in debug mode to check why it failed.
https://app.clickup.com/t/8696yzdfw
Also noticed a bug with S-BIAD1315 (can test with 'poetry run biaingest ingest --dryrun S-BIAD1315 -v -c --process-filelist skip') where the funding / grant objects were failing. I updated the code for these objects. Note that without 
--process-filelist skip it still fails for some reason (there's an empty filelist?) but that seems like a separate bug to investigate.
> Small bugs

- bia-ingest/bia_ingest/biostudies/v4/study.py
- bia-ingest/bia_ingest/cli_logging.py
Added code to catch invalid email addresses, and to record what's wrong with them in the output table. 
If an email address is found to be invalid, then it is made equal to None, and the contributor will still be recorded.
Where there are multiple errors of the same type, for any given study, then only one instance of this is recorded in the output table.
> Email validator

- bia-ingest/bia_ingest/biostudies/api.py
- bia-ingest/bia_ingest/biostudies/v4/image_acquisition_protocol.py
- bia-ingest/bia_ingest/cli.py
- bia-ingest/submission_overrides/biostudies/S-BIAD590/S-BIAD590_original.json
- bia-ingest/submission_overrides/biostudies/S-BIAD590/S-BIAD590_override.json
- bia-ingest/submission_overrides/biostudies/S-BIAD599/S-BIAD599_original.json
- bia-ingest/submission_overrides/biostudies/S-BIAD599/S-BIAD599_override.json
- bia-ingest/submission_overrides/biostudies/S-BIAD628/S-BIAD628_original.json
- bia-ingest/submission_overrides/biostudies/S-BIAD628/S-BIAD628_override.json
- bia-ingest/submission_overrides/biostudies/S-BIAD677/S-BIAD677_original.json
- bia-ingest/submission_overrides/biostudies/S-BIAD677/S-BIAD677_override.json
- bia-test-data/bia_test_data/mock_objects/mock_image_acquisition_protocol.py
- bia-test-data/data/biad_v4/S-BIADTEST.json
Prepared new jsons for ingest for 4 submissions that didn't have study component associations in the v4 template format, used option 2 in the related clickup ticket: https://app.clickup.com/t/86971jyhf
Las commit is for this ticket: https://app.clickup.com/t/86973tkc2
> 4submissions override

- bia-export/bia_export/website_export/export_all.py
- bia-export/bia_export/website_export/studies/retrieve.py
- bia-export/bia_export/website_export/studies/transform.py
Now correctly processes (and thefore will output) S-BIAD1480 before S-BIAD1407, even though they are released on the same data (was processing 1407 before 1480 resulting in the wonky order: https://deploy-preview-42--bia-beta-website.netlify.app/bioimage-archive/datasets/ )
Added info level log to help track how far through processing we are.
For some reason the file paths weren't working for the cache? They were last year... in any case i have updated them and they now work.
> added accession number to sort parameters for export

- api/api/api_logging.py
- api/api/app.py
- clients/python/example/pyproject.toml
https://app.clickup.com/t/86979zne5
Everything for all requests in a single log format, might need to reconsider if logs get too big
LE: extra fields added should help tell if a slow request should be slow because it's just big, or if there is an issue somewhere
> Better api logs

- .github/workflows/publish_container.yaml
- api/Readme.md
Forgot to setup buildx propperly in  https://github.com/BioImage-Archive/bia-integrator/pull/277, so fixing that here.
Tested in branch push first: https://github.com/BioImage-Archive/bia-integrator/actions/runs/12672067042
Issue: https://app.clickup.com/t/8697cy0x7
On macs, using the docker image published to github is stopping immediately with error:
exec /root/.local/bin/poetry: exec format error\n 
this is because the build is being created for amd architecture and not arm (apple MX chips). Using multi-platform builds creates images with an index pointing to different manifests for each platform.  (local) docker can pick whichever works on that architecture.
> Multi platform builds

- bia-assign-image/README.md
- bia-assign-image/bia_assign_image/cli.py
- bia-assign-image/tests/test_bia_assign_image_cli.py
The README was not congruent with the last set of changes, and this PR is related to the [clickup ticket](https://app.clickup.com/t/86973eygc) to update it. The following were also modified in light of team discussions:
* Make CLI commands default to use API
* Make `represenations create` command default to creating just the `UPLOADED_BY_SUBMITTER` representation
> Make cli default to API and update README

- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
Looking at the change, this shouldn't have any real effect - the objects now get turned to 'strings that are valid urls' when dumped & gain a trailing / if they didn't have one and don't have a fragment identifer.
> updated text expectations after pydantic version bump

- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
pydantic changed url serialization back in https://docs.pydantic.dev/latest/changelog/#v2106-2025-01-23, so returning tests to original state
> Fix shared-model-tests back to original states

- bia-export/bia-study-metadata.json
- bia-export/bia_export/cli.py
- bia-export/test.json
- bia-export/test/conftest.py
- bia-test-data/bia_test_data/data_to_api.py
Ticket: https://app.clickup.com/t/8697fg88f
Functionality allows us to just throw a bunch of files at the api (e.g. during test setup) and they will get created in the correct order.
Errors will be thrown if something is dodgy with the chain of dependencies
> added dependency based ordering to add_objects_to_api for testing

- bia-ingest/README.md
- bia-ingest/bia_ingest/biostudies/api.py
- bia-ingest/bia_ingest/biostudies/find_bia_studies.py
- bia-ingest/bia_ingest/cli.py
- bia-ingest/test/conftest.py
- bia-ingest/test/test_bia_ingest_cli.py
ticket: https://app.clickup.com/t/8697na58z
Note this currently just uses the 'ingested_submissions' file as reference for what has been ingested. This should really use the API but i would want to update some code in the config.py & create clients slightly differently in order to make testing against an api easier. This seems like a separate ticket / would make the PR really big like the one for export, so splitting it up here.
> added cli command that outputs uningested accession ids

- bia-converter-light/scripts/print_details_of_convertible_images.py
- bia-export/bia-study-metadata.json
- bia-export/bia_export/website_export/export_all.py
PR #280  deprecated the use of the `get_studies` method of the API. This PR updates the two places it was being used in the code base. [Clickup ticket ](https://app.clickup.com/t/8697qnjhj)
> Update instances using deprecated api_client method 'get_studies'

- bia-ingest/bia_ingest/biostudies/biostudies_default/default_dataset.py
- bia-ingest/bia_ingest/biostudies/biostudies_default/default_file_reference.py
- bia-ingest/bia_ingest/biostudies/submission_parsing_utils.py
- bia-ingest/bia_ingest/biostudies/v4/file_reference.py
- bia-ingest/bia_ingest/cli.py
- bia-ingest/test/conftest.py
- bia-ingest/test/test_biostudies_conversion.py
- bia-ingest/test/test_file_reference.py
- bia-test-data/bia_test_data/mock_objects/mock_dataset.py
- bia-test-data/bia_test_data/mock_objects/mock_file_reference.py
- bia-test-data/bia_test_data/mock_objects/mock_object_constants.py
- bia-test-data/data/default_biostudies/S-BSSTTEST.json
- bia-test-data/data/default_biostudies/S-BSSTTEST_files_direct.json
- bia-test-data/data/default_biostudies/file_list_default.json
- bia-test-data/data/default_biostudies/files_direct_default.json
For tickets:
https://app.clickup.com/t/8697b5yuc
https://app.clickup.com/t/8697c5vxm
To process and make tests for file references in default templates.
- Default study with a file list: https://www.ebi.ac.uk/biostudies/BioImages/studies/S-BSST51
- Default study with directly-attached files: https://www.ebi.ac.uk/biostudies/bioimages/studies/S-BSST1075
And the unusual submission, https://www.ebi.ac.uk/biostudies/bioimages/studies/S-BSST567, that has an effort at making associations. This, and any other studies like it (if they exist), will be caught, and a warning will be issued in the ingest output table.
> Process default file lists + tests

- bia-export/bia_export/website_export/studies/retrieve.py
- bia-ingest/bia_ingest/biostudies/generic_conversion_utils.py
- bia-ingest/bia_ingest/biostudies/v4/dataset.py
- bia-ingest/bia_ingest/cli_logging.py
- bia-shared-datamodels/src/bia_shared_datamodels/attribute_models.py
- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/test/test_attribute_models.py
Possible approach to attribute subclassing to create a single location / contract for other BIA packages to use.
Tested against local api using S-BIAD1285 - but would be good to have proper API testing for ingest to make sure it works - but not in scope of this PR. 
```
-------- Starting ingest of S-BIAD1285 --------
INFO     Fetching submission from https://www.ebi.ac.uk/biostudies/api/v1/studies/S-BIAD1285                                                                    api.py:229
INFO     Created Affiliation. Count: 1                                                                                                                  cli_logging.py:180
INFO     Created Affiliation. Count: 1 …
```
> created attribute subclasses for used across BIA packages

- bia-ingest/bia_ingest/biostudies/process_submission_v4.py
- bia-ingest/bia_ingest/biostudies/v4/dataset.py
- bia-ingest/test/test_bia_ingest_cli.py
- bia-ingest/test/test_biostudies_conversion.py
- bia-ingest/test/test_order_of_processing_datasets.py
- bia-test-data/data/biad_v4/file_list_annotations_and_images.json
Create file references for 'annotation' datasets before 'normal' datasets to address issue that file references can only point to one dataset. Creating those for 'normal' datasets last ensures that if annotation and normal datasets link to the same file, the file reference points to the 'normal' dataset.
Clickup ticket: https://app.clickup.com/t/8697r4bt4
> Create FileReferences for 'annotation' datasets before 'normal' ones

- .github/workflows/api.yaml
- .github/workflows/core.yaml
- Makefile
- bia-export/bia_export/cli.py
- bia-export/test/conftest.py
- bia-export/test/test_api_export.py
- bia-test-data/bia_test_data/data_to_api.py
- docker-compose.yml
Ticket: https://app.clickup.com/t/8697kxtgx
Scope creep: added a couple of tests that would have caught the recent changes to the api
> test new way of wiring up tests

- bia-assign-image/bia_assign_image/propose.py
- bia-assign-image/pyproject.toml
- bia-assign-image/tests/test_bia_assign_image_cli.py
- bia-assign-image/tests/test_propose.py
Allow yaml format to be used in addition to tsv format for proposing file references to convert to assign to images - [clickup ticket](https://app.clickup.com/t/86985ruc6)
> Make propose read and write to yaml as well as tsv

- api/api/models/elastic.py
- api/api/search.py
- api/api/tests/test_data/Readme.md
https://app.clickup.com/t/8698a6xhc
Seems ok for our usecase but might need to revisit and be clever with index generation.
TL;DR: we always want `"dynamic": false,`
> Update elastic indexed fields

- api/.env_compose
- api/.env_template
- api/api/models/elastic.py
- docker-compose.yml
https://app.clickup.com/t/8698a6z8h
Adds auth and an alternative viewer because keeping kibana meant either adding multi-step setup with an auth token or setting up separate role configs (for dev) - all overkill, might need to reconsider
> Enable auth for elastic, add alternative viewer

- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
We currently store an enum string like: CC_BY_4.0. If we were to instead store the url to the spec (i.e. https://creativecommons.org/licenses/by/4.0/ ) this would:
-  Be more interoperable across repositories, since the URI would the the same anywhere, but any string version of it is defined only by us.
-  Require fewer changes/mapping when it comes to ro-crate data - RO crate data requires a URI of a licence (note we still do some mapping from biostudies anyway, because there are typos etc)
- Doesn't allow us to use the value for more human readable display, but there is some formatting that still needs doing anyway (removing underscores) & this way we can also provide links out to the licences.
- I'm keeping it as an enum, to restrict which licences were available: which is the main …
> change licence enum to use full deed url

- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
Added channel label to signal channel info to allow a mapping from image data to dyes & signal frequency information - particularly useful when an image is composed of multiple channels, each from a different dye & imaging at different illumination frequencies.
ticket: https://app.clickup.com/t/8698nhwmm
> added channel label to signal-channel-information

- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
Updating title_id field to just title
The original name comes from the fact that certain objects in biostudies are referenced by their title in order to connect them to e.g. associations. However:
- Once the object is in the api, uuids are used to reference the object - the title_id only gets used as a title
- We now ingest data from other sources than biostudies, where the title is just a title, and not an id
It was also sort of being used as a way of indicating which objects a user was editing (in that it was a "user id'd object") - again this isn't the case with non-biostudies submission, and we hope to cover modelling this with this other PR: https://github.com/BioImage-Archive/bia-integrator/pull/329
> update title_id field name to title

- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
Update to image representation fields to make it clear that we expect single voxel size and not the physical size captured by the whole field of view. This aligns it with the OME-ZARR data model, that only captures the information for the single pixel.
Additionally, especially for EMPIAR sumbission, adding an optional label field for images for some kind of human-reable title would be useful for the website.
> added label field to image, and updated field names for physical dimensions of image representations

- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
Ticket: https://app.clickup.com/t/8698nhx0n
This reason for this PR was due to one of the issues encountered during getting EMPIAR data into the API / switching from the shared data models to the API models. Something should probably be changed to avoid issues, this solution is probably 1 of 2-3 options.
As an example, comparing the attribute field and the file_uri in image representations:
Generated models: 
- https://github.com/BioImage-Archive/bia-integrator/blob/main/clients/python/bia_integrator_api/models/image_representation.py
With fields:
-     attribute: Optional[List[Attribute]] = None
-     file_uri: List[StrictStr] = Field(description="URI(s) of the file(s) which together make up this image representation.")
Shared models: 
- …
> Make all Optional[List[]] fields only List[]

- bia-shared-datamodels/src/bia_shared_datamodels/attribute_models.py
- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
ticket: https://app.clickup.com/t/8698nhwmm
This PR aims to address our need to keep track of the source of data. Now that we have multiple ingestion sources and processes it is much less clear what the source of an object was.  We currently use AttributeProvenace to track the provenance of Attribute objects inside other objects. This extends the use of AttributeProvenance to a general Provenance enum for use on objects as well so we can capture source of objects. 
The change also includes renaming the attribute field to additional_metadata - which is somewhat more descriptive for such a general field - but importantly less confusing since attribute is an already overloaded term. 
Some areas which aren't addressed in the PR (yet) and would be good to encode in comments on the Provenance …
> changes to attributes, provenance, and adding document creator

- bia-shared-datamodels/src/bia_shared_datamodels/attribute_models.py
- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/test/test_attribute_models.py
Created sub-attribute to be used in any code that needs to create objects, in order to store the context of how the uuid was generated in the object sent to the api.
Only needed once uuid generation code has been merged from this branch.
> created uuid unique input attribute

- bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
- bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py
- bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
2 model changes:
1. remove use type from image rep models - this is because this information will be stored using attribute connections between the image and various image representations.
2. bump model version on all objects due to the addition of required fields - all objects have a new required field, and many objects have gone through somewhat significant change. Previous data would not be compatible, so a model version bump is sensible to signify the change.
Original ticket: https://app.clickup.com/t/8698nhx0n
And ticket i cut just to not forget about the change over the long weekend: https://app.clickup.com/t/8698xywp8
> remove use_type and object version bump

- bia-assign-image/scripts/map_image_related_artefacts_to_2025_04_models.py
- bia-assign-image/tests/test_data/migrate_to_2025_04_models/2025_04_models/image/S-BIAD609/71fb4f2d-6cff-495f-ae21-d1c6ab068de7.json
Clickup ticket: [https://app.clickup.com/t/86997e8kv](https://app.clickup.com/t/86997e8kv)
Note: attribute for uuid of im rep for zarr has a string value. However, attributes for static_display and thumbnail uris have list. Should I change the later 2 to string values as well - are there instances where we may need more than one value for these?
> Add uuid of im rep converted to zarr to attributes of 2025/04 image

- bia-ingest/bia_ingest/biostudies/common/study.py
Quick fix to ingest ~27 studies that were having issues with 'Uncaught exception: 'CC_BY-SA_30' '
E.g. to test:
poetry run biaingest ingest --dryrun --process-filelist skip S-BIAD867
> cover licences with dashes

- api/api/models/repository.py
- api/api/search.py
- api/api/tests/test_search_file_reference.py
https://app.clickup.com/t/8699f4tc5
Task: Add a method to the API that allows an API consumer to search for a FileReference using its exact path_name.
Background: to correctly create links between images in our database (via the API that controls interaction with Mongo), we want to be able to set a particular attribute on the file(s) that comprise that image. We have old curation code that enables this, but to make it work with the more recent version of the API, we'll need to add an API method that allows searching for a FileReference object using one of its attributes (path_name).
> Add search by path name

- bia-ingest/bia_ingest/biostudies/v4/annotation_method.py
Minor update to deal with studies like S-BIAD1377 and others where the method type attribute is repeately set (rather than using a comma separate string)
As part of: https://app.clickup.com/t/8699g3tg7
> updated annotation method logic to handle list like annotation types

- .github/workflows/core.yaml
- api/Dockerfile
- api/pyproject.toml
- bia-assign-image/pyproject.toml
- bia-converter/pyproject.toml
- bia-export/pyproject.toml
- bia-ingest/pyproject.toml
- bia-search/Dockerfile
- bia-search/pyproject.toml
- bia-test-data/pyproject.toml
Update all packages and docker containers to use python 3.13
Converter tests fail as they previously did (still need updating to use new models): https://github.com/BioImage-Archive/bia-integrator/actions/runs/15829077006/job/44616838925
Ticket: https://app.clickup.com/t/8699dnvmq
> test version bump to python 13

- bia-converter/bia_converter/cli.py
- bia-converter/bia_converter/ng_overlay.py
https://app.clickup.com/t/869a4uau2
Make create neuroglancer links runnable as a CLI tool in bia-converter
Updates
- get_ome_zar_file_uri: Gets the S3 url for the OME ZAR for an image
- annotation_filter: Study specific, but can be expanded in the future, to exclude certain annotations from the overlays
- update_additional_metadata_source_image_with_ng_view_url: Creates the attribute structure to add to the additional metadata of image object and updates the image object
- source_annotation_image_pairs: Finds the source and annotation image pairs using the api client
---
To test: 
```
source_image_uuid=0e00ab95-0da0-47f2-af67-6fbdc2ab05e2 # example UUID
poetry run bia-converter generate-neuroglancer-view-link --source-image-uuid $source_image_uuid
```
> add ng view link as CLI command

- api/pyproject.toml
Setting bcrypt version to 4.3 to avoid compatibility issues between passlib and bcrypt that causes api user creation to fail.
> fixed version of bcyrpt to 4.3 to avoid issue with passlib
