BioImage-Archive/bia-integrator

static-sitegen/scripts/generate_galleries_landing_page.py, static-sitegen/scripts/generate_image_page.py, static-sitegen/templates/base.html.j2, static-sitegen/templates/galleries-landing.html.j2
This pull request adds the creation of the galleries landing page and a minor bug fix in the generation of the image page.
=> Galleries landing page

.github/workflows/api.yaml, api/docker-compose.yml
@liviuba Is there any reason to go via ghcr for the api image when we can just build it?
=> Api container dep

.github/workflows/publish_container.yaml, Makefile, api/Makefile
Automatic building on api image
=> Automatic building on api image

data-migration/Readme.md, data-migration/pyproject.toml
Updated contents of Readme and packages imported by poetry
=> Update Readme and pyproject.toml for migration

.github/workflows/api.yaml, .gitignore, api/Dockerfile, api/Readme.md, api/docker-compose.yml, api/src/models/persistence.py, api/src/tests/test_biosample_specimen_image_acquisition.py
Fix the docker-compose-test CI job so that it gets the right vars and runs the api (so the tests run)
=> WIP add env vars?

bia-ingest/bia_ingest/visitor.py, bia-ingest/scripts/compare_biostudies_and_api_submission.py, bia-ingest/tests/test_assign_image_acquisitions_to_images_script.py, bia-ingest/tests/test_compare_biostudies_submission_with_api.py, bia-ingest/tests/test_handle_rembi_biosample.py, bia-ingest/tests/test_visitor_handles_api_biosample.py
Add script for comparing submissions in Biostudies with BIA API equivalents
=> Compare submission in biostudies and api

api/src/api/private.py, api/src/models/persistence.py, api/src/tests/test_annotations_collection.py, api/src/tests/test_annotations_fileref.py, api/src/tests/test_annotations_image.py, api/src/tests/test_annotations_study.py, api/src/tests/util.py
https://app.clickup.com/t/8694r2xw3
=> Remove test warnings

api/src/models/repository.py, api/src/tests/test_biosample_specimen_image_acquisition.py
Minor fixes addressing comments from last PR:
https://github.com/BioImage-Archive/bia-integrator/pull/108
=> minor improvements to code readability

bia-shared-datamodels/pyproject.toml, bia-shared-datamodels/src/bia_models/bia_data_model.py, bia-shared-datamodels/src/bia_models/semantic_models.py, bia-shared-datamodels/test/test_shared_models.py, bia-shared-datamodels/test/utils.py
Add tests for creation of all models in bia_data_model and minor tweaks to the various model definitions
=> Shared models v2

api/Dockerfile, api/pyproject.toml, api/src/api/private.py, api/src/api/public.py, api/src/app.py, api/src/log_config.yml, api/src/logging.py
https://app.clickup.com/t/8694zrnx5
=> Add json logs

bia-ingest-shared-models/README.md, bia-ingest-shared-models/bia_ingest_sm/biostudies.py, bia-ingest-shared-models/bia_ingest_sm/cli.py, bia-ingest-shared-models/bia_ingest_sm/config.py, bia-ingest-shared-models/bia_ingest_sm/conversion.py, bia-ingest-shared-models/pyproject.toml, bia-ingest-shared-models/test/data/S-BIADTEST.json, bia-ingest-shared-models/test/data/file_list_study_component_1.json, bia-ingest-shared-models/test/data/file_list_study_component_2.json, bia-ingest-shared-models/test/test_shared_models.py, bia-ingest-shared-models/test/utils.py, bia-shared-datamodels/src/bia_models/semantic_models.py
Create ExperiementalImagingDatasets, FileReferences, Biosample and ImageAnalysisMethod. Persist these to disk.
Because of time constraints the source code is sometimes verbose and needs refactoring. Additional notes:
* BioSample does not capture biological_entity
* FileReference.experimental_imaging_dataset.uuid is not yet implemented, current values are just copy of FileReference.uuid
* Persisting to disk messy (bia_data_dir env variable or .env file)
* Tested successfully on S-BIAD1026 and S-BIAD1250
* Failed on S-BIAD1260 (failed - zip files?) and  S-BIAD1040 (was taking too long > 100K files)
=> Ingest from biostudies version 2

bia-shared-datamodels/test/utils.py
Fix tests i broke in https://github.com/BioImage-Archive/bia-integrator/pull/127
=> updated shared model tests

docs/source/ingesting_and_converting.rst
=> path wrong in docs

bia-ingest-shared-models/bia_ingest_sm/conversion/file_reference.py
=> fix type hint

bia-ingest-shared-models/bia_ingest_sm/conversion/experimental_imaging_dataset.py, bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_growth_protocol.py, bia-ingest-shared-models/bia_ingest_sm/conversion/specimen_imaging_preparation_protocol.py
Make all the directory names of ingested artefacts plural
=> Make directory names of ingest artefacts consistently plural

bia-export/bia_export/cli.py, bia-export/bia_export/website_conversion.py, bia-export/bia_export/website_models.py, bia-export/test/output_data/bia_image_export.json, bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
which required adding model_rebuild() to some bia_datamodels
=> fixed export package & tests 

bia-export/bia_export/website_conversion.py, bia-export/bia_export/website_models.py, bia-export/test/input_data/file_references/S-BIADTEST/4bb8c5a4-d39f-4d9e-a112-334e859a5c22.json, bia-export/test/input_data/file_references/S-BIADTEST/ed89fa57-46a4-4ace-8d01-cc4504eb98e1.json, bia-export/test/output_data/bia_export.json
Added file count, image count, and file-type list (using suffix, rather than biostudies format) to datasets, to display information on website.
=> added file counts to website models

bia-ingest-shared-models/bia_ingest_sm/cli.py, bia-ingest-shared-models/bia_ingest_sm/cli_logging.py, bia-ingest-shared-models/bia_ingest_sm/conversion/annotation_method.py, bia-ingest-shared-models/bia_ingest_sm/conversion/image_annotation_dataset.py, bia-ingest-shared-models/bia_ingest_sm/conversion/utils.py, bia-ingest-shared-models/test/data/S-BIADTEST.json, bia-ingest-shared-models/test/test_bia_ingest_cli.py, bia-ingest-shared-models/test/test_shared_models.py, bia-ingest-shared-models/test/utils.py
Updated CLI to generate annotation method and image annotation datasets
Fixed file references for image annotation datasets failing to be created
Example study that now works: 
poetry run biaingest ingest S-BIAD916
=> Annotation dataset

bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
approved in: https://github.com/BioImage-Archive/bia-integrator/compare/new_licence but rebase made a mess of things so created new PR here.
=> added additional licence types

api/api/models/repository.py, api/api/private.py, api/api/tests/conftest.py, api/api/tests/test_minimal.py, bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
Adds update support to api
https://app.clickup.com/t/8695e0e11
=> Add update

api/helm-chart/templates/tests/test-connection.yaml
Fixes [this](https://github.com/BioImage-Archive/bia-integrator/actions/runs/10669617818/job/29571933319)
=> Fix failing api-test action

bia-export/bia_export/website_export/study_pages/retrieve.py, bia-export/bia_export/website_export/study_pages/transform.py, bia-export/bia_export/website_export/website_models.py, bia-export/test/input_data/annotation_methods/S-BIADTEST/ef019f5d-d3e0-4122-89ae-1d1d07d2830f.json, bia-export/test/input_data/derived_images/S-BIADTEST/7966aa52-e3db-4ce3-801e-44c524b73ee3.json, bia-export/test/input_data/file_references/S-BIADTEST/42cdf779-56c5-4a9e-9813-840f49071f79.json, bia-export/test/input_data/file_references/S-BIADTEST/fe7b5598-d089-4624-bbd6-21e68a0fe506.json, bia-export/test/input_data/image_annotation_datasets/S-BIADTEST/21999a9f-6f16-45d4-91c9-ed46cbfe015c.json, bia-export/test/output_data/bia_export.json
added export logic for annotation components, methods, and derived images
Also fixed if statement for images (!= should have been == to match dataset uuids)!
=> Annotation Export

api/.env_template, api/api/models/repository.py, api/api/tests/conftest.py, api/api/tests/test_minimal.py
https://app.clickup.com/t/8695j3phx
=> Add db timeout

api/api/models/repository.py
Fixes mismatched parameter name in https://github.com/BioImage-Archive/bia-integrator/pull/179
=> Fix dotenv argument name

bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py, bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
Add image_representation_type attribute to ImageRepresentation and update mock_objects to include a value for testing
=> Add attribute image_representation_type to ImageRepresentation

api/src/tests/util.py, clients/python/Readme.md, clients/python/example/private_api.py
https://app.clickup.com/t/8695j35te
=> Add initial client readme

api/api/public.py, api/api/tests/test_minimal.py
https://app.clickup.com/t/8695nv3nx
=> Add study list

bia-ingest-shared-models/bia_ingest_sm/cli.py, bia-ingest-shared-models/bia_ingest_sm/conversion/image_representation.py
Create command line utility to allow saving image representations to disk. This is useful until the API starts being used.
=> Save image representations to disk

clients/python/example/import_export_test_data.py
Minor changes to disk->api sync script
=> Import_export_cleanup

core/bia_integrator_core/config.py, core/dev/pyproject.toml, core/pyproject.toml, core/tests/test_annotations.py, core/tests/test_integrator.py, core/tests/test_studies.py, static-sitegen/requirements.txt, tools/bia_integrator_tools/conversion.py, tools/bia_integrator_tools/io.py, tools/dev/pyproject.toml, tools/pyproject.toml, tools/scripts/assign_images_from_yaml_BROKEN.py, tools/scripts/convert_local.py, tools/scripts/convert_to_zarr_and_upload.py
Make core module use old API (archived to clients/python_v1)
=> Make core module use old API (archived to clients/python_v1)

bia-ingest-shared-models/bia_ingest_sm/cli.py, bia-ingest-shared-models/bia_ingest_sm/config.py, bia-ingest-shared-models/bia_ingest_sm/conversion/experimentally_captured_image.py, bia-ingest-shared-models/bia_ingest_sm/conversion/image_representation.py, bia-ingest-shared-models/bia_ingest_sm/image_utils/conversion.py, bia-ingest-shared-models/bia_ingest_sm/image_utils/image_utils.py, bia-ingest-shared-models/bia_ingest_sm/image_utils/io.py, bia-ingest-shared-models/bia_ingest_sm/image_utils/omezarrmeta.py, bia-ingest-shared-models/bia_ingest_sm/image_utils/rendering.py, bia-ingest-shared-models/pyproject.toml, bia-ingest-shared-models/test/test_image_representation.py
First steps towards image conversion. Create command line tool to accept accession ID and uuid of file reference and convert to zarr and update image representations then save to disk
Most of the functions in the image_utils modules are needed temporarily whilst bia_converter is being developed, so some of them do not have type hints, and due to time pressures and the fact that they are temporary, these were not corrected.
=> Image conversion

bia-ingest/bia_ingest/conversion/experimentally_captured_image.py, bia-ingest/bia_ingest/conversion/image_representation.py, bia-ingest/bia_ingest/conversion/utils.py, bia-ingest/test/data/file_list_study_component_1.json, bia-ingest/test/test_conversion_util_funcs.py, bia-ingest/test/utils.py
* Use FileReference.file_path in creation of UUID for ECI to prevent errors when running tests on windows platform
* Add attributes from FileReference to ECI attributes
=> Update process to generate ExperimentallyCapturedImage

api/api/app.py, api/api/search.py, api/api/tests/test_search.py, clients/openapi.json, clients/python/bia_integrator_api/api/public_api.py, clients/python/bia_integrator_api/docs/PublicApi.md, clients/python/bia_integrator_api_README.md, clients/python/example/placeholder.py, clients/python/example/public.py
https://app.clickup.com/t/8695t1hgt
=> Add minimal search

bia-ingest/bia_ingest/conversion/experimental_imaging_dataset.py, bia-ingest/bia_ingest/conversion/experimentally_captured_image.py, bia-ingest/test/utils.py
Update associations of ExperimentalImagingDataset with uuids of biosample, image acquisition and specimen as discussed in [this clickup ticket]( https://app.clickup.com/t/8695tgh4j )
=> Add uuids of biosample, specimen and acquisition_process to EID attributes

bia-ingest/scripts/images-converted-for-sab.yaml
Add a yaml file containing file reference uuids and other details for image representations converted for the SAB
=> Add yaml containing file reference uuids of images converted for SAB

api/api/app.py, api/api/exceptions.py, api/api/models/api.py, api/api/models/repository.py, api/api/public.py, api/api/search.py, api/api/tests/test_minimal.py, api/api/tests/test_pagination.py, api/api/tests/test_search.py, clients/openapi.json, clients/python/bia_integrator_api/api/private_api.py, clients/python/bia_integrator_api/api/public_api.py, clients/python/bia_integrator_api/docs/PrivateApi.md, clients/python/bia_integrator_api/docs/PublicApi.md, clients/python/example/public.py
https://app.clickup.com/t/8695j4dpq
=> Api pagination

api/api/search.py, clients/openapi.json, clients/python/bia_integrator_api/api/private_api.py, clients/python/bia_integrator_api/docs/PrivateApi.md, clients/python/bia_integrator_api_README.md
https://app.clickup.com/t/86967kamj
=> Fix search not in private api

api/Readme.md, api/helm-chart/templates/deployment.yaml, api/helm-chart/values.yaml, api/pyproject.toml
Half of https://app.clickup.com/t/86964ygd3
=> Fix api image to match deployment, add new env vars to helm chart

api/helm-chart/Chart.yaml, api/helm-chart/values.yaml, api/pyproject.toml
bump version to force an upgrade
=> Bump image version for new models

.github/workflows/api.yaml, Makefile, clients/python/example/private_api.py, clients/python/example/public.py, docker-compose.yml
https://app.clickup.com/t/8696c1bc2
Needs https://github.com/BioImage-Archive/bia-integrator/pull/235
=> Setup client examples to run in ci

api/.env_template, api/api/app.py, api/api/settings.py, api/helm-chart/templates/deployment.yaml, api/helm-chart/values.yaml
https://app.clickup.com/t/8695pw50c
=> Api proxy root

api/Dockerfile, api/api/api_logging.py, api/api/app.py, api/api/log_config.yml
https://app.clickup.com/t/8696m5x23
=> Fix response_time_ms

bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py, bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py, bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
Updates to lots of classes to add an attribute field (done via mixin, as it seemed like this would help keep the name & design consistent in the future), and added requried title_id to Protocols
=> updated models with attributes and title_id

bia-ingest/bia_ingest/bia_object_creation_utils.py, bia-ingest/bia_ingest/cli.py, bia-ingest/bia_ingest/ingest/biosample.py, bia-ingest/bia_ingest/ingest/dataset.py, bia-ingest/bia_ingest/ingest/generic_conversion_utils.py, bia-ingest/bia_ingest/ingest/specimen.py, bia-ingest/bia_ingest/ingest/specimen_growth_protocol.py, bia-ingest/test/mock_objects/mock_association.py, bia-ingest/test/mock_objects/mock_biosample.py, bia-ingest/test/mock_objects/mock_dataset.py, bia-ingest/test/mock_objects/mock_specimen.py, bia-ingest/test/mock_objects/mock_specimen_growth_protocol.py, bia-ingest/test/test_bia_ingest_cli.py, bia-ingest/test/test_shared_models.py
Add growth protocol UUID to biosample -> biosamples are now unique to dataset associations where the biostudies specimen referred to has a growth protocol.
=> Add growth protocol UUID to biosample

api/Dockerfile, api/api/app.py, api/api/models/repository.py, api/api/settings.py, api/helm-chart/Chart.yaml, api/helm-chart/templates/deployment.yaml, api/helm-chart/values.yaml, api/pyproject.toml
For this https://app.clickup.com/t/8696kk2bj and this https://app.clickup.com/t/8696kmfu6
=> Small tweaks for better speed

bia-shared-datamodels/src/bia_shared_datamodels/mock_objects.py, bia-shared-datamodels/src/bia_shared_datamodels/semantic_models.py
added licence enum options and make Analysis and Correlation method models have optional fields
Also fix to tests failing on github due to different url types.
https://app.clickup.com/t/8696v6vyg
https://app.clickup.com/t/8696rzer5
Will update API client after this is merged.
=> Non-breaking model updates

bia-ingest/bia_ingest/biostudies/v4/study.py, bia-ingest/test/mock_objects/mock_study.py
https://app.clickup.com/t/8696v7aqr
=> add links to pagetab of original study in study attributes

api/api/models/repository.py
partial change for https://app.clickup.com/t/8696v9quk
=> UrlCodec -> AnyUrlCodec

api/api/auth.py, api/api/settings.py
https://app.clickup.com/t/8696zghvk
=> add jwt ttl

bia-export/bia_export/website_export/images/transform.py, bia-export/test/output_data/bia_image_export.json
Image export wasn't creating specimens, and biosample growth protocols weren't being filled in
=> fix specimen and biosample export for images

bia-export/bia_export/website_export/images/retrieve.py, bia-export/nextflow/.gitignore, bia-export/nextflow/README.md, bia-export/nextflow/nextflow.config_template, bia-export/nextflow/run_bia_export.nf, bia-export/nextflow/set_local_env.sh_template, bia-export/scripts/combine_export_files.py, bia-export/test/test_combine_export_files.py
* Fix minor bug due to missing page_size parameter in using api_client
* Create a nextflow script to run export of study, dataset and image metadata one accession ID at a time and an associated python script to merge the resulting jsons into one. See [https://app.clickup.com/t/86975pvwc](https://app.clickup.com/t/86975pvwc).
=> Nextflow scripts for export

.github/workflows/publish_container.yaml, api/Readme.md
=> update docker instructions and github action to perform multi-platform builds

api/api/public.py, api/api/tests/test_minimal.py
https://app.clickup.com/t/8697knck1
=> Add test for empty datasets

bia-export/README.md, bia-export/bia_export/cli.py, bia-export/bia_export/website_export/images/transform.py, bia-export/bia_export/website_export/studies/models.py, bia-export/bia_export/website_export/studies/retrieve.py, bia-export/test/output_data/bia-study-metadata.json
ticket: https://app.clickup.com/t/8697rdjuz
=> update export to use new dataset stats fields

.github/workflows/api.yaml, .github/workflows/core.yaml
https://app.clickup.com/t/8697r2xfn
=> Bump cache action

bia-assign-image/bia_assign_image/propose.py
A very small PR to fix bug in propose code resulting in same file being proposed more than once. [Clickup ticket](https://app.clickup.com/t/86986kxn6)
=> Fix bug in propose resulting in same file being proposed more than once

api/Readme.md
Related to https://github.com/BioImage-Archive/bia-integrator/pull/317
=> Add dejavu info in Readme

bia-assign-image/bia_assign_image/api_client.py, bia-assign-image/tests/test_store_object_in_api_idempotent.py
Clickup ticket: [https://app.clickup.com/t/8698pbpje](https://app.clickup.com/t/8698pbpje)
=> Fix minor bug when updating version during persistence using API

bia-shared-datamodels/src/bia_shared_datamodels/uuid_creation.py
Ticket: https://app.clickup.com/t/8698nhwmm
Doc: https://docs.google.com/document/d/1TxkOvf7z24OR90ljVVIhXDbK2r-a7S7OVNraYImzp0A/edit?tab=t.qieduw1hg7fs
Note, branch is set to be merged into Model update branch
=> uuid creation updates

bia-shared-datamodels/src/bia_shared_datamodels/bia_data_model.py
Fix to make object_creator not a field on User objects
=> Object creator fix

bia-export/bia_export/website_export/studies/retrieve.py
https://app.clickup.com/t/86998b5na
=> Update export for model updates

bia-assign-image/bia_assign_image/cli.py, bia-assign-image/bia_assign_image/image_assignment.py, bia-assign-image/bia_assign_image/object_creation/creation_process.py, bia-assign-image/bia_assign_image/object_creation/image.py, bia-assign-image/bia_assign_image/object_creation/image_representation.py, bia-assign-image/bia_assign_image/object_creation/specimen.py, bia-assign-image/scripts/map_image_related_artefacts_to_2025_04_models.py, bia-assign-image/tests/conftest.py, bia-assign-image/tests/test_assign_image.py, bia-assign-image/tests/test_assign_image_with_pattern.py, bia-shared-datamodels/src/bia_shared_datamodels/package_specific_uuid_creation/shared.py
ticket: https://app.clickup.com/t/8699v7w9j
use functions defined in: https://github.com/BioImage-Archive/bia-integrator/pull/384
required some fixes to functions
=> make image assignment use new uuid funcs

bia-ingest/bia_ingest/biostudies/biostudies_default/default_dataset.py, bia-ingest/bia_ingest/biostudies/biostudies_default/default_file_reference.py, bia-ingest/bia_ingest/biostudies/common/study.py, bia-ingest/bia_ingest/biostudies/v4/annotation_method.py, bia-ingest/bia_ingest/biostudies/v4/bio_sample.py, bia-ingest/bia_ingest/biostudies/v4/dataset.py, bia-ingest/bia_ingest/biostudies/v4/file_reference.py, bia-ingest/bia_ingest/biostudies/v4/growth_protocol.py, bia-ingest/bia_ingest/biostudies/v4/image_acquisition_protocol.py, bia-ingest/bia_ingest/biostudies/v4/specimen_imaging_preparation_protocol.py, bia-shared-datamodels/src/bia_shared_datamodels/package_specific_uuid_creation/biostudies_ingest_uuid_creation.py
update ingest to use new functions plus created function for default biostudies template
Should be a 'no-op' change
=> Using new uuid functions - ingest

bia-export/scripts/elastic_refresh.sh, bia-search/Makefile, bia-search/helm-chart/.helmignore, bia-search/helm-chart/Chart.yaml, bia-search/helm-chart/templates/NOTES.txt, bia-search/helm-chart/templates/_helpers.tpl, bia-search/helm-chart/templates/deployment.yaml, bia-search/helm-chart/templates/ingress.yaml, bia-search/helm-chart/templates/secrets.yaml, bia-search/helm-chart/templates/service.yaml, bia-search/helm-chart/values.yaml
For https://app.clickup.com/t/8699na3h1
Adds a Helm chart to deploy the search api, deployed now
=> Add search helm chart

bia-search/Readme.md, bia-search/helm-chart/templates/deployment.yaml
https://app.clickup.com/t/8699vwg5v
Fixes docs at https://alpha.bioimagearchive.org/search/docs
=> Add readme / fastapi base path config

bia-converter/bia_converter/convert.py, bia-shared-datamodels/src/bia_shared_datamodels/package_specific_uuid_creation/empair_ingest_uuid_creation.py, bia-shared-datamodels/src/bia_shared_datamodels/package_specific_uuid_creation/image_conversion_uuid_creation.py
update convert to use new uuid creations functions when creating new images
ticket: 8699v7w9j
=> bia convert to use new creation functions

.vscode/settings.json, bia-assign-image/.vscode/settings.json, bia-assign-image/scripts/fix_additional_metadata.py, bia-assign-image/scripts/map_image_related_artefacts_to_2025_04_models.py, bia-assign-image/tests/test_data/migrate_to_2025_04_models/2025_04_models/image/EMPIAR-10326/0c51b3ea-256d-43c6-a648-26ed787a6b62.json, bia-assign-image/tests/test_data/migrate_to_2025_04_models/2025_04_models/image/S-BIAD609/71fb4f2d-6cff-495f-ae21-d1c6ab068de7.json, bia-assign-image/tests/test_fix_image_additional_metadata_static_uri.py, bia-assign-image/tests/test_fix_image_additional_metadata_thumbnail_uri.py, bia-converter/scripts/assign_and_convert_images.sh
Make migration script use latest uri format. [Clickup ticket](https://app.clickup.com/t/8699v8bf3)
=> Fix image additional metadata

api/api/app.py
https://app.clickup.com/t/8699n52at
=> Remap non-internal server error

ro-crate-ingest/override_data/empiar/EMPIAR-ANNOTATIONTEST/ANNOTATIONTEST.json, ro-crate-ingest/override_data/empiar/EMPIAR-ANNOTATIONTEST/data/ribosomes/Tomograms/05/IS002_291013_005.mrc, ro-crate-ingest/override_data/empiar/EMPIAR-ANNOTATIONTEST/data/ribosomes/Tomograms/06/IS002_291013_005.mrc, ro-crate-ingest/ro_crate_ingest/empiar_to_ro_crate/empiar/entry_api.py, ro-crate-ingest/ro_crate_ingest/empiar_to_ro_crate/empiar/file_api.py, ro-crate-ingest/ro_crate_ingest/empiar_to_ro_crate/entity_conversion/dataset.py, ro-crate-ingest/test/empiar_to_ro_crate/output_data/EMPIAR-ANNOTATIONTEST/ro-crate-metadata.json, ro-crate-ingest/test/empiar_to_ro_crate/proposal/empiar_annotationtest.yaml, ro-crate-ingest/test/test_empiar_to_ro_crate.py
ticket:  https://app.clickup.com/t/8699n7gp8
follow up to: https://github.com/BioImage-Archive/bia-integrator/pull/398
=> fix some empiar rembi / annotation handling

ro-crate-ingest/ro_crate_ingest/save_utils.py
=> fix post to api when re-running on the same study

bia-search/Dockerfile, bia-search/api/search.py
https://app.clickup.com/t/8699v5rrg
=> Update search docker image to include dependencies for refresh

bia-assign-image/scripts/map_image_related_artefacts_to_2025_04_models.py, bia-assign-image/tests/test_data/migrate_to_2025_04_models/2025_04_models/image/EMPIAR-10326/0c51b3ea-256d-43c6-a648-26ed787a6b62.json, bia-assign-image/tests/test_data/migrate_to_2025_04_models/2025_04_models/image/S-BIAD609/71fb4f2d-6cff-495f-ae21-d1c6ab068de7.json, bia-assign-image/tests/test_data/migrate_to_2025_04_models/test_update_example_image_uri/image/S-BIAD-MAP-IMAGE-RELATED-ARTEFACTS-TO-2025-04-MODELS-TEST/321af7aa-4299-4ad2-9ab6-f1ac50b28174.json, bia-assign-image/tests/test_update_dataset_example_image_uri_after_mapping_to_2025_04_models.py
Clickup ticket: [https://app.clickup.com/t/869a1rc8c](https://app.clickup.com/t/869a1rc8c)
=> Update instances of static_display_uri to correct name and other minor fixes to migration script

bia-converter/README.md, bia-converter/pyproject.toml, bia-converter/scripts/generate_neuroglancer_link.py
script for generating neuroglancer overlayed images links
=> script for generating links

bia-ingest/bia_ingest/biostudies/v4/image_analysis_method.py, bia-ingest/bia_ingest/biostudies/v4/image_correlation_method.py, bia-ingest/bia_ingest/cli.py, bia-test-data/data/biad_v4/S-BIADTEST.json
Updates for changes due to ST introducing Biostudies.v5 template. Clickup ticket: [https://app.clickup.com/t/869a6ndaa](https://app.clickup.com/t/869a6ndaa)
=> Update ingest for v5 template

bia-converter/scripts/generate_neuroglancer_link.py
https://app.clickup.com/t/869a4c0ry
Script updates - 
handles channels in overlays by reading the data from OME ZAR
Input - 
source and annotated image urls  - This will be changed to UUID in the next PR
and layout - optional
Output - 
Neuroglancer overlayed URL
----
to test example:
```
source_image_url=https://uk1s3.embassy.ebi.ac.uk/bia-integrator-data/S-BIAD1659/1e02db9b-d273-4562-a95e-e78d78c26fd7/510f7a97-9b9a-41bc-8a97-8c9d5a605c1c.ome.zarr/0;
annotation_image_1_url=https://uk1s3.embassy.ebi.ac.uk/bia-integrator-data/S-BIAD1659/cb06d5dc-cb93-4891-94bb-bd68ace22190/4dc2ce9d-503d-448b-99b1-ba9b7c6f082c.ome.zarr/0;
poetry run python3 scripts/generate_neuroglancer_link.py --source-image-url $source_image_url --annotation-image-urls $annotation_image_1_url ;
```
=> handle channels for overlays

bia-ingest/bia_ingest/biostudies/api.py, bia-ingest/submission_overrides/biostudies/S-BIAD2250/S-BIAD2250_original.json, bia-ingest/submission_overrides/biostudies/S-BIAD2250/S-BIAD2250_override.json
https://app.clickup.com/t/869a9zrcp
- Specimen title not matching with the relations
=> Override for S-BIAD2250

ro-crate-ingest/override_data/biostudies/S-BSST_PAGETAB_FILES/S-BSST_PAGETAB_FILES_override.json, ro-crate-ingest/ro_crate_ingest/biostudies_to_ro_crate/biostudies/submission_api.py, ro-crate-ingest/ro_crate_ingest/biostudies_to_ro_crate/biostudies_conversion.py, ro-crate-ingest/ro_crate_ingest/biostudies_to_ro_crate/entity_conversion/bio_sample.py, ro-crate-ingest/ro_crate_ingest/biostudies_to_ro_crate/entity_conversion/contributor.py, ro-crate-ingest/ro_crate_ingest/biostudies_to_ro_crate/entity_conversion/file_list.py, ro-crate-ingest/ro_crate_ingest/biostudies_to_ro_crate/entity_conversion/pagetab_file.py, ro-crate-ingest/ro_crate_ingest/biostudies_to_ro_crate/entity_conversion/taxon.py, ro-crate-ingest/test/biostudies_to_ro_crate/output_data/S-BSST_PAGETAB_FILES/Default template. No Study Components/filelist.tsv, ro-crate-ingest/test/biostudies_to_ro_crate/output_data/S-BSST_PAGETAB_FILES/ro-crate-metadata.json, ro-crate-ingest/test/test_biostudies_to_ro_crate.py
added processing for default template bsst submissions where the files are placed in the pagetab
ticket: https://app.clickup.com/t/8699zncyr
Also removed some unused imports, and neatened up global variable setting, as it was causing issue when multiple tests were run.
=> Generate ro-crate from bsst submissions files in pagetab
